export const customerConstants = {
    GET_CUSTOMERS_PENDING: "GET_CUSTOMERS_PENDING",
    GET_CUSTOMERS_SUCCESS: "GET_CUSTOMERS_SUCCESS",
    GET_CUSTOMERS_FAILURE: "GET_CUSTOMERS_FAILURE",

    DELETE_CUSTOMERS_PENDING: "DELETE_CUSTOMERS_PENDING",
    DELETE_CUSTOMERS_SUCCESS: "DELETE_CUSTOMERS_SUCCESS",
    DELETE_CUSTOMERS_FAILURE: "DELETE_CUSTOMERS_FAILURE",
};